project:
  type: website

website:
  title: "ECLIPSE Presentations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cheat_sheet.html
        text: Cheat Sheet
       
engine: jupyter
jupyter: python3

format:
  html:
    theme:
      dark: darkly
      light: flatly      
    css: styles.css
    toc: true
 