project:
  type: website

website:
  title: "ECLIPSE Presentations"
  navbar:
    left:
      - href: index.qmd
        text: Home
       

format:
  html:
    theme:
      dark: darkly
      light: flatly      
    css: styles.css
    toc: true
 