project:
  type: website

website:
  title: "ECLIPSE Presentations"
  navbar:
    left:
      - href: index.qmd
        text: Home
       
engine: jupyter
jupyter:
  python: r"C:\Users\braun\AppData\Local\Microsoft\WindowsApps\python.exe"

format:
  html:
    theme:
      dark: darkly
      light: flatly      
    css: styles.css
    toc: true
 