project:
  type: website

website:
  title: "ECLIPSE Presentations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cheat_sheet.html
        text: Cheat Sheet
       
execute:
  echo: true
  eval: true
  python: true
  python-version: "3"
  python-venv: ".venv"
  python-path: ".venv/Scripts/python.exe"

format:
  html:
    theme:
      dark: darkly
      light: flatly      
    css: styles.css
    toc: true
 
 