---
title: "Public Presentations of the ECLIPSE group"
---
[Pelz Lab website](https://pelzlab.science)

# Talks

[2025 M&M:  Sub-Ångstrom 3D Resolution, Large-Volume Imaging and Automation Advances in Electron Ptychography](conference_talks/2025_MandM/template.html)

# Tutorials

[4D STEM Concepts and applications in the physical and life sciences - STEM Ptychographyn](conference_talks/2025_MC/template.html)






# Data Science for Electron Microscopy
[Lecture 1: Introduction](data_science_for_em/01_intro/template.html)

[Lecture 2: Regression](data_science_for_em/02_regression/template.html)

[Lecture 3: Convolutional Neural Networks](data_science_for_em/03_cnns/template.html)

[Lecture 4: CNN Classification & Self-supervised Learning](data_science_for_em/04_selfsupervised/template.html)

[Lecture 5: Generative Adversarial Networks](data_science_for_em/05_gan/template.html)

[Lecture 6: Gaussian Processes](data_science_for_em/06_gaussian_processes/template.html)

[Lecture 7: Gaussian Processes 2](data_science_for_em/07_gaussian_processes2/template.html)

[Lecture 8: Imaging Inverse Problems](data_science_for_em/08_imaging_inverse_problems1/template.html)

[Lecture 9: Imaging Inverse Problems 2](data_science_for_em/09_imaging_inverse_problems2/template.html)

---



# Code Examples (Materials Data Science Book)

## Mathematical Foundations of AI & ML

### 01_learning_vs_data_analysis
- [11.2_How_and_what_do_Machines_Learn.ipynb](mathematical_foundations_of_ai_and_ml/01_learning_vs_data_analysis/example_notebooks/11.2_How_and_what_do_Machines_Learn.html)
- [11.5_Data_Preprocessing.ipynb](mathematical_foundations_of_ai_and_ml/01_learning_vs_data_analysis/example_notebooks/11.5_Data_Preprocessing.html)
- [11.8_Similarity_Measures_for_Classification_Problems.ipynb](mathematical_foundations_of_ai_and_ml/01_learning_vs_data_analysis/example_notebooks/11.8_Similarity_Measures_for_Classification_Problems.html)
- [14.3_Notions_and_Concepts_for_Classification_Problems.ipynb](mathematical_foundations_of_ai_and_ml/01_learning_vs_data_analysis/example_notebooks/14.3_Notions_and_Concepts_for_Classification_Problems.html)
- [14.4_Nearest_Neighbor_Classifier.ipynb](mathematical_foundations_of_ai_and_ml/01_learning_vs_data_analysis/example_notebooks/14.4_Nearest_Neighbor_Classifier.html)
- [3.2_sets_tuples_vectors_arrays.ipynb](mathematical_foundations_of_ai_and_ml/01_learning_vs_data_analysis/example_notebooks/3.2_sets_tuples_vectors_arrays.html)
- [3.3_representation_of_data_in_ML.ipynb](mathematical_foundations_of_ai_and_ml/01_learning_vs_data_analysis/example_notebooks/3.3_representation_of_data_in_ML.html)

### 02_linear_algebra_pca_svd
- [15.2_PCA__Theoretical_Background_and_Derivations.ipynb](mathematical_foundations_of_ai_and_ml/02_linear_algebra_pca_svd/example_notebooks/15.2_PCA__Theoretical_Background_and_Derivations.html)
- [15.3_Application_Aspects_and_Examples_of_PCA.ipynb](mathematical_foundations_of_ai_and_ml/02_linear_algebra_pca_svd/example_notebooks/15.3_Application_Aspects_and_Examples_of_PCA.html)

### 03_regression_as_loss_minimization
- [12.1_General_Concepts_and_Important_Terminology.ipynb](mathematical_foundations_of_ai_and_ml/03_regression_as_loss_minimization/example_notebooks/12.1_General_Concepts_and_Important_Terminology.html)
- [12.3_Simple_Linear_Regression.ipynb](mathematical_foundations_of_ai_and_ml/03_regression_as_loss_minimization/example_notebooks/12.3_Simple_Linear_Regression.html)
- [12.5_A_Worked_Example_of_Simple_Linear_Regression.ipynb](mathematical_foundations_of_ai_and_ml/03_regression_as_loss_minimization/example_notebooks/12.5_A_Worked_Example_of_Simple_Linear_Regression.html)
- [12.6_Multiple_Linear_Regression_Models.ipynb](mathematical_foundations_of_ai_and_ml/03_regression_as_loss_minimization/example_notebooks/12.6_Multiple_Linear_Regression_Models.html)
- [13.2_Generalized_Formulations_and_Vectorization.ipynb](mathematical_foundations_of_ai_and_ml/03_regression_as_loss_minimization/example_notebooks/13.2_Generalized_Formulations_and_Vectorization.html)
- [13.4_Formulation_of_Chosen_Cases_in_Terms_o_Basis_Functions.ipynb](mathematical_foundations_of_ai_and_ml/03_regression_as_loss_minimization/example_notebooks/13.4_Formulation_of_Chosen_Cases_in_Terms_o_Basis_Functions.html)
- [13.5_Semi_and_Non-Parametric_Regression.ipynb](mathematical_foundations_of_ai_and_ml/03_regression_as_loss_minimization/example_notebooks/13.5_Semi_and_Non-Parametric_Regression.html)

### 04_neural_networks_activations
- [17.2_The_Rosenblatt_Perceptron.ipynb](mathematical_foundations_of_ai_and_ml/04_neural_networks_activations/example_notebooks/17.2_The_Rosenblatt_Perceptron.html)
- [17.4_Increasing_the_Complexity__Assemblies_of_Neurons.ipynb](mathematical_foundations_of_ai_and_ml/04_neural_networks_activations/example_notebooks/17.4_Increasing_the_Complexity__Assemblies_of_Neurons.html)

### 05_backpropagation_gradient_flow
- [18.3_Backpropagation--Introduction_and_Example.ipynb](mathematical_foundations_of_ai_and_ml/05_backpropagation_gradient_flow/example_notebooks/18.3_Backpropagation--Introduction_and_Example.html)
- [18.5_Python_Implementation_and_Example_for_the_FCN.ipynb](mathematical_foundations_of_ai_and_ml/05_backpropagation_gradient_flow/example_notebooks/18.5_Python_Implementation_and_Example_for_the_FCN.html)

### 08_probabilistic_view_of_learning
- [10.10_The_Covariance_Matrix_and_Multivariate_Normal_Distribution.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/10.10_The_Covariance_Matrix_and_Multivariate_Normal_Distribution.html)
- [10.11_Lognormal_Distribution.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/10.11_Lognormal_Distribution.html)
- [10.13_Logistic_Distribution.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/10.13_Logistic_Distribution.html)
- [10.2_Discrete_Uniform_Distribution.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/10.2_Discrete_Uniform_Distribution.html)
- [10.3_Bernoulli_Distribution.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/10.3_Bernoulli_Distribution.html)
- [10.4_Binomial_Distribution.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/10.4_Binomial_Distribution.html)
- [10.5_Geometric_Distribution.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/10.5_Geometric_Distribution.html)
- [10.6_Poisson_Distribution.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/10.6_Poisson_Distribution.html)
- [10.7_Normal_Distribution.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/10.7_Normal_Distribution.html)
- [10.8_Bivariate_Normal_Dsitribution.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/10.8_Bivariate_Normal_Dsitribution.html)
- [14.5_Gaussian_Naive_Bayes_Model.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/14.5_Gaussian_Naive_Bayes_Model.html)
- [5.1_Combinatorics.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/5.1_Combinatorics.html)
- [5.2_Probabilities.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/5.2_Probabilities.html)
- [7.1_expected_values.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/7.1_expected_values.html)
- [8.4_Sampling_Strategies.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/8.4_Sampling_Strategies.html)
- [8.5_The_Law_of_Large_and_Truly_Large_Numbers.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/8.5_The_Law_of_Large_and_Truly_Large_Numbers.html)
- [8.6_Central_Limit_Theorem.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/8.6_Central_Limit_Theorem.html)
- [8.7_Covariance_and_Correlation.ipynb](mathematical_foundations_of_ai_and_ml/08_probabilistic_view_of_learning/example_notebooks/8.7_Covariance_and_Correlation.html)

### 10_latent_spaces_embeddings
- [19.5_Generative_Adversarial_Networks.ipynb](mathematical_foundations_of_ai_and_ml/10_latent_spaces_embeddings/example_notebooks/19.5_Generative_Adversarial_Networks.html)

## ML for Characterization and Processing

### unit01_intro
- [11.2_How_and_what_do_Machines_Learn.ipynb](ml_for_characterization_and_processing/unit01_intro/example_notebooks/11.2_How_and_what_do_Machines_Learn.html)

### unit02_physics_of_data
- [4.2_Datasets_used_in_the_Book.ipynb](ml_for_characterization_and_processing/unit02_physics_of_data/example_notebooks/4.2_Datasets_used_in_the_Book.html)

### unit03_data_quality
- [11.5_Data_Preprocessing.ipynb](ml_for_characterization_and_processing/unit03_data_quality/example_notebooks/11.5_Data_Preprocessing.html)
- [9.2_Two_Preliminiary_Steps.ipynb](ml_for_characterization_and_processing/unit03_data_quality/example_notebooks/9.2_Two_Preliminiary_Steps.html)
- [9.3_Descriptive_Statistics.ipynb](ml_for_characterization_and_processing/unit03_data_quality/example_notebooks/9.3_Descriptive_Statistics.html)

# Additional Resources
[Cheat Sheet](cheat_sheet.html)


