---
title: |-
  Data Science for Electron Microscopy<br>
  Lecture 6: Gaussian Processes 1
author:
- name: Philipp Pelz
  affiliation:
  - FAU Erlangen-Nürnberg
bibliography: ref.bib
csl: custom.csl
execute:
  eval: true
  echo: true
format:
  revealjs:
    chalkboard: true
    width: 1920
    height: 1080
    template-partials:
    - title-slide.html
    css: custom.css
    theme: custom.scss
    slide-number: c/t
    logo: eclipse_logo_small.png
    background-transition: fade
    incremental: false
    menu:
      side: left
      loadIcons: true
    footer: ©Philipp Pelz - FAU Erlangen-Nürnberg - Data Science for Electron Microscopy
---
{{< include 00_learning_objectives.qmd >}}
 
   
                         
<!-- {{< include gaussian_processes.qmd  >}}    -->
{{< include 05_gp1.qmd >}} 
{{< include 05_gp2.qmd >}} 
{{< include 05_gp3.qmd >}}

{{< include 01_notation_guide.qmd >}}
## Scalability references to revisit

::: {.smaller}
- Sparse variational inducing-point GPs for dense data regimes: [@hensman_gaussian_2013].
- BBMM/GPyTorch and preconditioned conjugate gradients for scalable exact GP inference: [@gardner_gpytorch_2018; @wang_exact_2019].
- SGD-based posterior sampling for large-scale or ill-conditioned GP regression: [@lin_sampling_2023].
:::

<!-- BEGIN prev-next -->

## Continue

- &larr; Previous: [Unit 05 &mdash; GANs](../05_gan/template.html)
- &rarr; Next: [Unit 07 &mdash; Gaussian Processes II](../07_gaussian_processes2/template.html)
- [All courses](../../index.html)

<!-- END prev-next -->

## References   
::: {#refs} 
:::



 






































<script>
document.getElementById("marimo-frame").onload = function() {
    try {
        let iframeDoc = document.getElementById("marimo-frame").contentWindow.document;
        let marimoBadge = iframeDoc.querySelector("div.fixed.bottom-0.right-0.z-50");
        if (marimoBadge) {
            marimoBadge.style.display = "none";
            console.log("Marimo badge hidden successfully.");
        } else {
            console.log("Badge not found.");
        }
    } catch (error) {
        console.warn("Unable to modify iframe content due to CORS restrictions.");
    }
};
</script>
</div>