name: Build and Deploy Quarto Presentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: latest

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build Presentations
        run: |
          quarto render data_science_for_em/02_regression/template.qmd --to revealjs
          quarto render data_science_for_em/01_intro/template.qmd --to revealjs

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            data_science_for_em/02_regression/template_files/figure-revealjs
            data_science_for_em/01_intro/template_files/figure-revealjs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 